spring:
  config:
    import: 'aws-parameterstore:'
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  #spring Oauth2 기능 추가
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 354627486864-qfnhmonlb4kklbtdq1glqf4j5k1q36m7.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  aws:
    paramstore:
      enabled: true
      prefix: /spring-boot-aws
      name: pre-029
      profile-separator: _



server:
  port: 8085
  ssl:
    key-store: {}
    key-store-type: {}
    key-store-password: {}
#logging:
#  level:
#    org:
#      springframework:
#        orm:
#          jpa: DEBUG

# classpath:localhost.p12
# PKCS12
# changeit