server:
  port: 8085

spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://rds-pre-029.cnuf9an3lpvk.ap-northeast-2.rds.amazonaws.com:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: Eulja2013*
  drive-class-name: com.mysql.cj.jdbc.Driver