server:
  port: 8084
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: jungdo8016@gmail.com
    password: ijfjzvldnhndzzvf
    auth: true
    starttls:
      enable: true
  subject:
    member:
      registration: Nice Meet you! We are Iguana!
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print


#logging:
#  level:
#    org:
#      springframework:
#        orm:
#          jpa: DEBUG